import type { Metadata } from "next";

// components
import { oswald, roboto } from "@/components/shared/fonts";
import Header from "@/components/shared/header";

import "./globals.css";
import { TailwindIndicator } from "@/components/shared/tailwind-indicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} ${roboto.className} antialiased`}>
        <Header />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
